name: API Testing with Newman

on:
  push:
    branches: [ main ]

jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests
        run: newman run "Contact API testing.postman_collection.json" -d contact_data.csv --reporters cli,html --reporter-html-export report.html



